### ISSUE TITLE
during environment creation system does not allow to create different size containers, only tiny size

### ISSUE THREAD

**Issue by bkelceoglu** [subutai-io/Subutai#13]
i have faced this problem several times. at the moment we can only create a tiny containers which is not enough ie appscale. 
trying to allocate or extend the size with karaf shell or subutai quota binding did not worked too.

**Comment by soffokl** [comment]
@Dilshat @ztimur, please look at this problem. Looks like it is not related to @subutai-io/sysnet 
We cannot create other types of containers because have only one strategy.

**Comment by tjamakeev** [comment]
@bkelceoglu please check limits of peers with CLI peer:limits <peer_id>. It shows RH limits. To successfully create an environment you should have enough resources in the participated RH.
Quota CLI does not help in this case, because it dealing with LXC quotas.

**Comment by tjamakeev** [comment]
Implemented unlimited container placement strategy.
