### ISSUE TITLE
Different templates in "containers" row after each page reload

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/Subutai#17]
If you have more then one environment, open "Environments" tab and you will see the following:
![image](https://cloud.githubusercontent.com/assets/13515865/12939367/fdf6cec4-cfe8-11e5-9c84-a43c19f966ed.png)
F5, and look at "containers" row:
![image](https://cloud.githubusercontent.com/assets/13515865/12939369/05c38cd2-cfe9-11e5-8c07-c966d66b9a43.png)
"Hadoops" environment is made of hadoop template, second one is masters.
Seems like a bug.

**Comment by larenso** [comment]
fixed
