### ISSUE TITLE
Agent fails to reconnect after SS redeploy

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/Subutai#19]
Steps to reproduce:

1. Setup peer with 2 RHs. First time after approval both agents connect normally
2. Redeploy SS inside MH container. Agents don't reconnect until restarted. Tested on develop/devel

**Comment by soffokl** [comment]
@Dilshat could you give more information about "Redeploy SS inside MH"? Do you using some script for that, or can you describe steps?

**Comment by Dilshat** [comment]
`#####################################
service management stop

cd /root
mkdir temp
tar xf subutai-4.0.0-RC6.tar.gz -C /root/temp/

#####################################
rm -rf /var/lib/apps/subutai-mng/current/*
echo Removed Subutai DB ...
#####################################

rm -rf /apps/subutai-mng/current/system
rm -rf /apps/subutai-mng/current/lib
rm -rf /apps/subutai-mng/current/deploy

echo Removed old files of karaf ...

cp -a /root/temp/subutai*/system /apps/subutai-mng/current/system
cp -a /root/temp/subutai*/lib /apps/subutai-mng/current/lib
cp -a /root/temp/subutai*/deploy /apps/subutai-mng/current/deploy
cp /root/temp/subutai*/etc/subutai-mng/git.properties /apps/subutai-mng/current/etc/subutai-mng/
cp /root/temp/subutai*/etc/subutai-mng/quota.cfg /apps/subutai-mng/current/etc/subutai-mng/

rm -r /root/temp/

######################################
# Set DEBUG MODE #####################
sed 's/# export KARAF_DEBUG/export KARAF_DEBUG=true/g' /apps/subutai-mng/current/bin/setenv > setenv && mv setenv /apps/subutai-mng/current/bin
######################################
service management start

echo Management Started successfully !!!

#######################################                                                                           

`

**Comment by soffokl** [comment]
Hm, I have repeated all steps using devel from Subutai-snappy repository and develop from Subutai repository. 

Both agents successfully connected and requested approval again. It takes some time to resolve all timeouts, but it works. 
Reconnect shouldn't take more than 1 minute, for me it about 15-20 seconds.

**Comment by soffokl** [comment]
Fixed problem when Subutai Agent looped without trying reconnect to MH.
If Agent was not approved and at this moment MH was replaced, Agent
didn't send new connect request. 

Fixed in #22
